[tool.poetry]
name = "music-publisher-bot"
version = "0.1.0"
description = "Telegram бот для публикации аудио с картинкой"
authors = ["Твое Имя <email@example.com>"]

[tool.poetry.dependencies]
python = "^3.10"
aiogram = "^2.25.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
