[tool.poetry]
name = "your_project_name"
version = "0.1.0"
description = "A bot for publishing to Telegram"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.11"
flask = "^2.2"
aiogram = "^3.0.0" # используем актуальную версию
