[tool.poetry]
name = "audio-bot"
version = "0.1.0"
description = "Telegram bot for posting audio and image to channel"
authors = ["Vive <vitocorocovo@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
aiogram = "^2.25"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
